### ISSUE TITLE
Setup error "driver/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0)"

### ISSUE THREAD

**Issue by enochii** [QilinPTA/Qilin#1]
Hi, really good works~

When I tried the docker image by following the instruction in Qilin wiki, I got output below. It says `driver/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0)`. By the way, when I cloned the repo and ran it in my WSL, same things happened.

Is it anything I missed? Thanks~

```shell
root@dce6d3699656:/qilin# python3 run.py antlr ci -print
now running insens for antlr ...
-Xmx256g -timeout=43200 -pae -pe -clinit=ONFLY -lcs -mh -pta=insens -apppath benchmarks/dacapo2006/antlr.jar -libpath benchmarks/dacapo2006/antlr-deps.jar -reflectionlog benchmarks/dacapo2006/antlr-refl.log -mainclass dacapo.antlr.Main -jre=jre1.6.0_45
java -Xms1g -Xmx256g -cp /qilin/Qilin-1.0-SNAPSHOT.jar driver.Main -pae -pe -clinit=ONFLY -lcs -mh -pta=insens -apppath benchmarks/dacapo2006/antlr.jar -libpath benchmarks/dacapo2006/antlr-deps.jar -reflectionlog benchmarks/dacapo2006/antlr-refl.log -mainclass dacapo.antlr.Main -jre=/qilin/benchmarks/JREs/jre1.6.0_45
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: driver/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

**Comment by enochii** [comment]
Thanks~
